{% set CONDA_PY = os.environ.get('CONDA_PY', '36') %}
name: gibbs-py{{ CONDA_PY }}

dependencies:
  - python=3.6
  - attrs
  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - altair
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - sympy
  - git
  - pylint
  - pygmo
  - thermo

  # For tests
  - pytest
  - pytest-lazy-fixture
  - pytest-cov
  - codecov
  - hypothesis
  - nbval

environment:
  PYTHONPATH:
    - {{ root }}
  GIBBS_NOTEBOOKS_DIR: {{ root }}/notebooks
  PY_VERSION: {{ CONDA_PY }}
